---
title: "607_Project2_DylanGold"
format: html
editor: visual
---

## Approach

In this project we have to practice tidying and analysis of datasets. We are to pick 2 other datasets from the dicussion 5A posts, as well as our own. Tidy up these datasets through things like pivot_longer and such and perform some analysis through some tables, visualizations and brief interpretations.\

First, I will definitely pick my own data set, https://www.kaggle.com/datasets/eugeniyosetrov/renewable-power-plants?select=renewable_capacity_timeseries.csv\
This dataset is wide, having both the types of energy and countries combined into columns. I will probably create some time series line plots to visualize the data and talk about how energy consumption has increased or decreased over time, compare different sources and countries of energy.

For my second dataset I will pick https://www.kaggle.com/datasets/aungdev/birth-rate-of-countries-world-bank-data?utm_source=chatgpt.com&select=API_SP.DYN.CBRT.IN_DS2_en_csv_v2_5607611.csv  This dataset was found by the classmate Khandker Qaiduzzaman. This dataset has several problems with being untidy. It needs to be made longer due to having multiple years as columns. Another problem having redundant, seemingly irrelevant columns with a repeated value in practically every row, and its columns headers are in a row by default. Some analysis that can be done is showing the rate of change in birthrate in countries, looking at which countries have the largest/smallest change or largest/smallest flat amount. It looks like the data is already normallized per 1000 people.

For my third dataset I will probably pick https://edgar.jrc.ec.europa.eu/report_2024?vis=co2tot#data_download\
This dataset is from Muhammad Khan, who posted a link to https://en.wikipedia.org/wiki/List_of_countries_by_carbon_dioxide_emissions#Fossil_carbon_dioxide_emissions_by_country\
He was discussing the 2000 and 2023 columns. From the source data we can see we have multiple years 1970s to 2020s, as columns. This makes it very wide. It also has multiple tables in the xlxs file for which I will maybe pick some or 2 I am interested in to consolidate. I may change my mind about this dataset because it is very large for github, but hopefully I can download it directly from the site. From this dataset I can also show the changes in total emissions or emissions per capita and more. There are a lot of countries, so i will probably focus on finding the largest emissions and showing the increase in that for a time series line plot visualization
